- name: generate-snake-game-from-github-contribution-grid
  uses: Platane/snk@v2.0.0-rc.2
  with:
    # github user name
    code-parth:
    # list of files to generate.


- palette: a preset of color, one of [github, github-dark, github-light]
- color_snake: color of the snake
- color_dots: coma separated list of dots color. The first one is the empty cell color, the second one is the lightest shade, the third one is the second lightest shade ect ...

  outputs: |
    dark.svg?palette=github-dark&color_snake=blue
    light.svg?color_snake=#7845ab
    ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

    outputs: # optional
