name: Generate

on:
  schedule: # execute every 1 hours
    - cron: "* */1 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v1.1.0
          with:
            github_user_name: ${{ code-parth }}
            svg_out_path: dist/github-snake.svg
      
      - uses: crazy-max/ghaction-github-pages@v2.1.3
          with:
            target_branch: output
            build_dir: dist
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
